# Generated by Django 6.0 on 2025-12-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdmodel',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
